sudo: required
dist: trusty
language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

deploy:
  provider: releases
  api_key:
    secure: ZgVFPOyf4PHr/ikM3mCLi39wkhuww3d7N9PSDqOBV56HQqzPUS+bHxxRiGSg4EnHNIjna4mS9eY05HuLIfBDeWiua/p6Fjzxn4jxmEgurnCE86Oqy3ONCtjOxcjjiXA2oqxqF0i6v3B6YouyV6UlhQihSTOFDKyVk50EnB5VOR64pBDW/NZJL/edJ9CuOzfbp8jBuzfJyGp++bUXW84vcmF7a2Wdz/AwoHMav5C8O6LhHEPS7LDbkNLjU+rlHHjDvuTX5sjnKHDP82FBVhHCzvcznga1fh0p7muIoDv+c4kFfK6eVj9ig0lk5CN3Kpl8sUx9Kw3R4t00epBb5Y6uY5Gby/0tdzIgYRw7qZ09Iqh9btrj8SVThG+cBZq86vYLvvxIIHF5oX2V2q97RbHEEvqd8x6K7rkkz/qH9Td6AiPIVybrPWwxLQodeU5UEfGCOD7FI7VjtF0VR2MgmKS7ZOVOcvw7VNrdDohWlgbIvx1Gqh5roTwkpFdI8dirlAl8ilAlAu/VX0bssCMSGtL4OQCDvvhcMl2iFqgse481NMex0YtbpbYY/Z9HLidAR2/L3whoLS9FGECgWnxxNbM8mNBHhJkFLJV7Lmxs9W5CA+tsrJL32Cx+xmRAGQkYn4wwmMCv4F0MacfvP5tCjbnys7k1y2tofSFPcCizpIgGRq4=
  file: target/release/fireplace
  skip_cleanup: true
  on:
    tags: true
    repo: Drakulix/fireplace

env:
  global:
    secure: p3ikgPx2e9m91C35EUhXqkvyN0bGy8UnXbX2S2DQLoJnCd9z8t31s7kImbJVvFeRH0bpcr+2//WIgGvWpefgG6W3O7HoqBWP5RZqdXRgJU8roE1JmOqgqRE9xfzu+fyzQHbkuiKTx96WhmCKm1bwtT+REX+3oaixUCJ64bGuNb9N6hGiq4QN10H7Sy5N7g9Ow4buQRQa9MUxv/dOYcRZ7u38UW3RVjgPSyxgGFsmyQpeIMVQxJyqdVWKEEoAE1zCzbqCPnIIQjsaDXnJLPERApvyC2u/+ZnJ3KowJ5Hs0M5PFMSjjdLKATdTd42mic6QWsxpWpMvQUHo6juGfg49wo6oOPyAtkCfSZpHBK+Av7vjtGfXiNLWvaMoNjEDzCV5A4fykKJmbRiRuYMsd0mwGvstZkV8Y7ItIr5/jwE6Zgq2MuzHS49y4accNvXrZ+GS0+y6ysimw/bWfkwB2qtN0tSPZ/G8ibx6kx4/WYIdKJ+34YkDNxC3ip5mE0AhVXF3xOzZsfAt+Fd5hrZ+FMxi7gns49Bkm23MctmG7Rr5t+VfW3QffSh2b0a5Otlnwf0kCYNZIWgOr8CeojInsEVtPmEG0u789trmeGMFavSa9iluDEIGVwctwwNT9ex1a/3j3HhGAfCL7muaSlgd0ALgv7dhL2WbeS69x20QcBQc+AU=

before_script:
- 'echo ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/ > ~/.vagga.yaml'
- 'echo alpine-mirror: http://mirrors.gigenet.com/alpinelinux/ >> ~/.vagga.yaml'
- |
  echo "$(id -un):100000:65536" | sudo tee /etc/subuid | sudo tee /etc/subgid
  sudo apt-get install uidmap -y
  curl http://files.zerogw.com/vagga/vagga-install-testing.sh | sh

script:
- vagga check-fmt
- vagga clippy
- vagga build
- vagga doc

after_success:
- vagga --use-env=GH_TOKEN doc_upload
