[workspace]
members = [
    "fireplace",
    "fireplace_lib",
    "fireplace_flavors/json",
    "fireplace_flavors/code",
]

[profile.release]
lto = true

[replace]
"fireplace_lib:2.0.1" = { path = "./fireplace_lib" }
